pipeline {
    agent {
	docker {
			image 'maven:3.8.1-adoptopenjdk-11'
			args '-v /root/.m2:/root/.m2'
		}
	}
    stages {
	 stage('Init'){
	 steps{
        def dockerHome = tool 'myDocker'
        env.PATH = "${dockerHome}/bin:${env.PATH}"
	 }
    }
        stage('Build') { 
            steps {
                sh 'mvn -B -Dskiporder-functional-tests package' 
            }
        }
        stage('Test') { 
            steps {
                sh 'mvn test'
            }
        }
    }
}