pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -Dskiporder-functional-tests package' 
            }
        }
        stage('Test') { 
            steps {
                sh 'mvn test'
            }
        }
    }
}